server:
  port: 1112
spring:
  application:
    name: eureka-client
eureka:
  client:
    securePortEnabled: true
    ssl:
      key-store: codesheepclient.p12
      key-store-password: codesheep.cn
    serviceUrl:
      defaultZone: https://localhost:1111/eureka/
